language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: c7oHzO5TA50rp4fAeyeREBDUjbzOeT8AK3BQ7d6kDlkA+ic7RbO5aEUx9rkdCYv+fFbuRj8MTa7UBCirK34wkSli1mWT0guFqlEliURZg4owwl3Z2w1yQ465VTmIVZxUZeh/ebXbya6Nv0HGVeSzq9LluvDUYU7ViJg+pYXkWvW460GOEcncbCejetkVtEbJ+8n1lAG7g24nmG9LC6YIY7YUAirUTMwNJ5m1cE0hOhzGSAQEJKQNHEhHDMYvtHfxNAltzyNyVfqZokKebZywzhxVqydVvSYY1SFZIhBuyvjftn6UqpGULNTtAFLytHcKpSfJt+8tDefa2WC8RgBMz61RIfFMClLQcekC2SUagkFL2JFT7/V84L0JiiSd2NB7TP0zYiQ0Pvt63I8AhdZ+qkyss5Jikv8DweA+DcpdjuPUIHqnltPN8EtTBl5E/kGjis46jUYaO1Jxz1jZ7IFdv7vvYGCNI7lvh1IrGufg+kAno+wRQzVSWIZ/3s7xCPAtG8MHvvZGNVrDD0EN/ZW20o88VcH93x2DtLr4tpuLeGwuAy69lGHXTYL9FiwuF+LjxlakyiaxrwpBm7ILHpstpWrLnQeknI8EfuniEHfakaUmdj1dyYH89ypkFbQJupbEpbtC3wrAaHgJgJdZfql7Rdw1zfY7UTFRXudDb0xbXX4=
  app: jmaxwell-fullstack-client
  on:
    repo: maxjeffwell/full-stack-capstone-client
