language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
install:
  - npm install
script: true
env:
- CI=true
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: Y2DnOGB1+Hb3Vf/1Ab3t2Q5I/j0cEAReLd9wT9Cuf51j3k8zSL9RhkMDx673RjVSsBJNUxfMgi3V+m3PBi2NiREwrM5JuB+ebLqSIKlzN142T4t7Hj67txoofYhQf9TTRPgS2lrBY485LNgEi6I83Eq74qLLbNGjNPHdWZFkTM3FElrhGSxMxBL2UB08+H0/b6lGv2OdDzyoKXh6eZf4yI8HiNb0Iexw87/TlhBOqCZv59Fi6t05zv2emIap3y8lbzBmgteuN+TOmk9SfmQP91k+GvUZg7rxVNZ9xTJV0QnFwWg2IYK1u6ZCmrb2+voNeI+6VFohbG6h1n9iE3aVutk5EF+gJ1Az57AWQ8vwiKqYl+irUiV4OQaHqZK22GmSgn033rfHAC7of9eQDbLngH2vtrDOdWo0kuX5Wobn+qsclbBeGUFP5+ioNAxGaXbTFzHAboQx6JKmr6sqQenEkJW6BSlbC5e5xOpS/H1xr5WQWHGdVHfM5ZJQ2Mf18u5Dhi12w5TdhoE4nG6XKI01BPqhtXrhgfTvOLO8rTry/5bmr9ZwH0RNmP3mhvc9Ft63Uhsg/ZZ4dQo/an2GDcJJ5G2HCWlbHxs6txafriFBKoV+B/bDILAGBobm4e/P5HtCZqTMxmcOwbmKX2reMAGBLoanmaJvG/Yps4li0oR3z5k=
  app: jmaxwell-fullstack-client
  on:
    repo: maxjeffwell/full-stack-capstone-client
